name: image2pdf_easyconvert
description: Image to PDF Converter
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.8.5+3
  image: ^4.2.0
  permission_handler: ^11.3.1
  pdf: ^3.6.0
  media_scanner: ^2.0.0
  external_path: ^1.0.3
  gap: ^3.0.1
  loading_animation_widget: ^1.2.0+4
  open_file: ^3.3.2
  share_plus: ^9.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  flutter_plugin_android_lifecycle: ^2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true